Test_Name = 'VI_SNS_turn_on'
print(f'............ {Test_Name} ........')
from dfttools import *
from time import sleep
from Procedures import Global_enable
# setting 3.072MHz clock from PLL
BLCK_Set_1 = 3.072e6                          # 3.072MHz
I2C_WRITE(device_address="0x38",field_info={'fieldname': 'pll_mode', 'length': 2, 'registers': [{'REG': '0x84', 'POS': 6, 'RegisterName': 'PLL_REG_5', 'RegisterLength': 8, 'Name': 'pll_mode[1:0]', 'Mask': '0xC0', 'Length': 2, 'FieldMSB': 1, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '17', 'User': '000YYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=hex(2))      #dig_pll_freerun_en_vddd=0
I2C_WRITE(device_address="0x38",field_info={'fieldname': 'pll_p', 'length': 6, 'registers': [{'REG': '0x81', 'POS': 0, 'RegisterName': 'PLL reg 2', 'RegisterLength': 8, 'Name': 'pll_p[5:0]', 'Mask': '0x3F', 'Length': 6, 'FieldMSB': 5, 'FieldLSB': 0, 'Attribute': '00NNNNNN', 'Default': '06', 'User': '000YYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=hex(6))         #dig_pll_prediv_vddd<5:0>=6d 
I2C_WRITE(device_address="0x38",field_info={'fieldname': 'pll_n', 'length': 6, 'registers': [{'REG': '0x82', 'POS': 0, 'RegisterName': 'PLL reg 3', 'RegisterLength': 8, 'Name': 'pll_n[5:0]', 'Mask': '0x3F', 'Length': 6, 'FieldMSB': 5, 'FieldLSB': 0, 'Attribute': '00NNNNNN', 'Default': '18', 'User': '000YYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=hex(18))        #dig_pll_n<5:0>=24d 
I2C_WRITE(device_address="0x38",field_info={'fieldname': 'pll_ldet_cnt', 'length': 5, 'registers': [{'REG': '0x83', 'POS': 0, 'RegisterName': 'PLL reg 4', 'RegisterLength': 8, 'Name': 'pll_ldet_cnt[4:0]', 'Mask': '0x1F', 'Length': 5, 'FieldMSB': 4, 'FieldLSB': 0, 'Attribute': '000NNNNN', 'Default': '10', 'User': '000YYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=hex(10)) #rfu_pll_ldet_cnt<4:0>=16d
FREQFORCE(signal="IOCLK0",reference="GND",value=BLCK_Set_1)                          #BCLK frequency=3.072MHz
sleep(0.0001)                                                                    #wait 100us
# VI sense turn on procedure
I2C_WRITE("0x38", {'fieldname': 'vis_channel_v_en', 'length': 1, 'registers': [{'REG': '0xA7', 'POS': 0, 'RegisterName': 'Vis enables reg', 'RegisterLength': 8, 'Name': 'vis_channel_v_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '000000NN', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]}, 1)
I2C_WRITE("0x38", {'fieldname': 'vis_dac_v_en_m', 'length': 1, 'registers': [{'REG': '0x0B', 'POS': 0, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_dac_v_en_m', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 1)
I2C_WRITE("0x38", {'fieldname': 'vis_sarmute_v_m', 'length': 1, 'registers': [{'REG': '0x0B', 'POS': 1, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_sarmute_v_m', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}	, 0)
I2C_WRITE("0x38", {'fieldname': 'vis_int_res_v_m', 'length': 1, 'registers': [{'REG': '0x0B', 'POS': 2, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_int_res_v_m', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 0)
I2C_WRITE("0x38", {'fieldname': 'vis_digres_v_m', 'length': 1, 'registers': [{'REG': '0x0B', 'POS': 3, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_digres_v_m', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 3, 'FieldLSB': 3, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 0)
I2C_WRITE("0x38", {'fieldname': 'vis_channel_i_en', 'length': 1, 'registers': [{'REG': '0xA7', 'POS': 1, 'RegisterName': 'Vis enables reg', 'RegisterLength': 8, 'Name': 'vis_channel_i_en', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': '000000NN', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]}, 1)
I2C_WRITE("0x38", {'fieldname': 'vis_dac_i_en_m', 'length': 1, 'registers': [{'REG': '0x0C', 'POS': 0, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_dac_i_en_m', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 1)
I2C_WRITE("0x38", {'fieldname': 'vis_sarmute_i_m', 'length': 1, 'registers': [{'REG': '0x0C', 'POS': 1, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_sarmute_i_m', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}	, 0)
I2C_WRITE("0x38", {'fieldname': 'vis_int_res_i_m', 'length': 1, 'registers': [{'REG': '0x0C', 'POS': 2, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_int_res_i_m', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 0)
I2C_WRITE("0x38", {'fieldname': 'vis_digres_i_m', 'length': 1, 'registers': [{'REG': '0x0C', 'POS': 3, 'RegisterName': 'Forcing reg 1', 'RegisterLength': 8, 'Name': 'vis_digres_i_m', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 3, 'FieldLSB': 3, 'Attribute': '0000NNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]}, 0)