from dfttools import *
from time import sleep
from Procedures.Startup import startup
from Procedures.Global_enable import global_enable
from Procedures.Playback import playback

def offset_cal_cld_3lvl():
  Test_Name = 'Offset_cal_cld_3lvl'
  print(f'............ {Test_Name} ........')
  startup()
  global_enable()
  playback()
  v1 = VMEASURE("OUTP","OUTN",0,0)
  print(f'"OUTP" - "OUTN" before calibration {v1}')
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'i2c_page_sel', 'length': 1, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '0x00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'spk_en', 'length': 1, 'registers': [{'REG': '0x9F', 'POS': 0, 'RegisterName': 'Enables settings 5', 'RegisterLength': 8, 'Name': 'spk_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000S', 'Default': '0x00', 'User': '0000000Y', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_mode', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 1, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_mode', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': 'NNNNNNNN', 'Default': '0x83', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'vis_adc_clk_pol_v', 'length': 1, 'registers': [{'REG': '0xA6', 'POS': 2, 'RegisterName': 'Vis modulator reg', 'RegisterLength': 8, 'Name': 'vis_adc_clk_pol_v', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': '0000NNNN', 'Default': '0x00', 'User': '0000000Y', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_offs_steps', 'length': 4, 'registers': [{'REG': '0x76', 'POS': 4, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_steps[3:0]', 'Mask': '0xF0', 'Length': 4, 'FieldMSB': 3, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x83', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0xF) # {'fieldname': 'cal_offs_steps', 'length': 4, 'registers': [{'REG': '0x76', 'POS': 4, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_steps[3:0]', 'Mask': '0xF0', 'Length': 4, 'FieldMSB': 3, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x83', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} default is 8 calibration, with bit (1111) makes 15 calibration (suggested)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_offs_inv_sign', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 3, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_inv_sign', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 3, 'FieldLSB': 3, 'Attribute': 'NNNNNNNN', 'Default': '0x83', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'offs_comp_en', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 0, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'offs_comp_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x83', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x1) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_offs_ext_thr', 'length': 3, 'registers': [{'REG': '0x77', 'POS': 4, 'RegisterName': 'CAL reg 2', 'RegisterLength': 8, 'Name': 'cal_offs_ext_thr[2:0]', 'Mask': '0x70', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x2A', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_offs_int_thr', 'length': 3, 'registers': [{'REG': '0x77', 'POS': 0, 'RegisterName': 'CAL reg 2', 'RegisterLength': 8, 'Name': 'cal_offs_int_thr[2:0]', 'Mask': '0x7', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x2A', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_offs_avg', 'length': 3, 'registers': [{'REG': '0x78', 'POS': 4, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_offs_avg[2:0]', 'Mask': '0x70', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x7) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_grp_delay', 'length': 2, 'registers': [{'REG': '0x78', 'POS': 2, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_grp_delay[1:0]', 'Mask': '0xC', 'Length': 2, 'FieldMSB': 1, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x3) 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'cal_dws_sample_rate', 'length': 2, 'registers': [{'REG': '0x78', 'POS': 0, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_dws_sample_rate[1:0]', 'Mask': '0x3', 'Length': 2, 'FieldMSB': 1, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x3)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'ivfb_v_invert_en', 'length': 1, 'registers': [{'REG': '0xA0', 'POS': 2, 'RegisterName': 'Data invert Reg', 'RegisterLength': 8, 'Name': 'ivfb_v_invert_en', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x1)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'input_cm_en', 'length': 1, 'registers': [{'REG': '0x17', 'POS': 0, 'RegisterName': 'Input cm settings 1', 'RegisterLength': 8, 'Name': 'input_cm_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': 'NNNNNN0N', 'Default': '0x35', 'User': 'YYYYY0YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0) #  {'fieldname': 'input_cm_en', 'length': 1, 'registers': [{'REG': '0x17', 'POS': 0, 'RegisterName': 'Input cm settings 1', 'RegisterLength': 8, 'Name': 'input_cm_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': 'NNNNNN0N', 'Default': '0x35', 'User': 'YYYYY0YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]}=0
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'spk_gain', 'length': 3, 'registers': [{'REG': '0x92', 'POS': 0, 'RegisterName': 'SPK setting reg 1', 'RegisterLength': 8, 'Name': 'spk_gain[2:0]', 'Mask': '0x7', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': '000NNNNN', 'Default': '0x03', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x5) #{'fieldname': 'spk_gain', 'length': 3, 'registers': [{'REG': '0x92', 'POS': 0, 'RegisterName': 'SPK setting reg 1', 'RegisterLength': 8, 'Name': 'spk_gain[2:0]', 'Mask': '0x7', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': '000NNNNN', 'Default': '0x03', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]}=5 (101)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'i2c_page_sel_1', 'length': 1, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel_1', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '0x00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x1)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'otp_offset_ext_gain1', 'length': 9, 'registers': [{'REG': '0xC7', 'POS': 0, 'RegisterName': 'OTP FIELDS 23 - TRACEABILITY 11', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 5, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[8]', 'Mask': '0x20', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'otp_offset_int_gain1', 'length': 9, 'registers': [{'REG': '0xC9', 'POS': 0, 'RegisterName': 'OTP FIELDS 25', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 3, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[8]', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x0)
  # cal start >/ Push button 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'i2c_page_sel', 'length': 1, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '0x00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_REG_WRITE(0x38,0x79,0x1,1)
  sleep(0.2)
  #*********
  cal_offs_end_value = I2C_READ(device_address="0x38",field_info={'fieldname': 'cal_offs_end', 'length': 1, 'registers': [{'REG': '0x79', 'POS': 4, 'RegisterName': 'CAL reg 4', 'RegisterLength': 8, 'Name': 'cal_offs_end', 'Mask': '0x10', 'Length': 1, 'FieldMSB': 4, 'FieldLSB': 4, 'Attribute': '00RR000P', 'Default': '0x00', 'User': 'YYYYYYYY', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG0'}]},expected_value=0x1)
  cal_offs_result_value = I2C_READ(device_address="0x38",field_info={'fieldname': 'cal_offs_result', 'length': 1, 'registers': [{'REG': '0x79', 'POS': 5, 'RegisterName': 'CAL reg 4', 'RegisterLength': 8, 'Name': 'cal_offs_result', 'Mask': '0x20', 'Length': 1, 'FieldMSB': 5, 'FieldLSB': 5, 'Attribute': '00RR000P', 'Default': '0x00', 'User': 'YYYYYYYY', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG0'}]},expected_value=0x1)
  print(f'cal_offs_end_value : {hex(cal_offs_end_value)} , cal_offs_result_value :{hex(cal_offs_result_value)} ')
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'i2c_page_sel', 'length': 1, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '0x00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x0)
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'spk_en', 'length': 1, 'registers': [{'REG': '0x9F', 'POS': 0, 'RegisterName': 'Enables settings 5', 'RegisterLength': 8, 'Name': 'spk_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000S', 'Default': '0x00', 'User': '0000000Y', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]},write_value=0x1)
  v1 = VMEASURE("OUTP","OUTN",0,0)
  print(f'"OUTP" - "OUTN" befoer calibration {v1}')
 
  I2C_WRITE(device_address="0x38",field_info={'fieldname': 'i2c_page_sel_1', 'length': 1, 'registers': [{'REG': '0xFE', 'POS': 0, 'RegisterName': 'Page selection', 'RegisterLength': 8, 'Name': 'i2c_page_sel_1', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '0000000N', 'Default': '0x00', 'User': '000000YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x1)
  ext_offset_comp = I2C_READ(device_address="0x38",field_info={'fieldname': 'otp_offset_ext_gain1', 'length': 9, 'registers': [{'REG': '0xC7', 'POS': 0, 'RegisterName': 'OTP FIELDS 23 - TRACEABILITY 11', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 5, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[8]', 'Mask': '0x20', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},expected_value=0x7)
  int_offset_comp = I2C_READ(device_address="0x38",field_info={'fieldname': 'otp_offset_int_gain1', 'length': 9, 'registers': [{'REG': '0xC9', 'POS': 0, 'RegisterName': 'OTP FIELDS 25', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 3, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[8]', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},expected_value=0x7)
  print(f'{Test_Name} :> ext_offset_comp : {hex(ext_offset_comp)}, int_offset_comp : {hex(int_offset_comp)}')
  # if ext_offset_comp < 7 :
  #   I2C_WRITE(device_address="0x38",field_info={'fieldname': 'otp_offset_ext_gain1', 'length': 9, 'registers': [{'REG': '0xC7', 'POS': 0, 'RegisterName': 'OTP FIELDS 23 - TRACEABILITY 11', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 5, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_ext_gain1[8]', 'Mask': '0x20', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x7)
  # elif int_offset_comp < 7:
  #   I2C_WRITE(device_address="0x38",field_info={'fieldname': 'otp_offset_int_gain1', 'length': 9, 'registers': [{'REG': '0xC9', 'POS': 0, 'RegisterName': 'OTP FIELDS 25', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[7:0]', 'Mask': '0xFF', 'Length': 8, 'FieldMSB': 7, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}, {'REG': '0xCB', 'POS': 3, 'RegisterName': 'OTP FIELDS 27', 'RegisterLength': 8, 'Name': 'otp_offset_int_gain1[8]', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 8, 'FieldLSB': 8, 'Attribute': 'NNNNNNNN', 'Default': '0x00', 'User': '00000000', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG1'}]},write_value=0x7)
  # else:
  #   pass 
    
if __name__ == '__main__':
  offset_cal_cld_3lvl()