from dfttools import *
from time import sleep
import random

Test_Name = 'Offset_cal_cld_intfb'
from Procedures import Startup
from Procedures import Global_enable
print(f'............ {Test_Name} ........')

# da rfu bit {'fieldname': 'ivfb_v_invert_en', 'length': 1, 'registers': [{'REG': '0xA0', 'POS': 2, 'RegisterName': 'Data invert Reg', 'RegisterLength': 8, 'Name': 'ivfb_v_invert_en', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': 'NNNNNNNN', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} va messo a 1
#metto {'fieldname': 'spk_gain', 'length': 3, 'registers': [{'REG': '0x92', 'POS': 0, 'RegisterName': 'SPK setting reg 1', 'RegisterLength': 8, 'Name': 'spk_gain[2:0]', 'Mask': '0x7', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': '000NNNNN', 'Default': '03', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} a 5, sono 3 bit
# {'fieldname': 'cld_pskip_cm_force', 'length': 1, 'registers': [{'REG': '0x18', 'POS': 1, 'RegisterName': 'Force registers 1', 'RegisterLength': 8, 'Name': 'cld_pskip_cm_force', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': '00NNNNNN', 'Default': '00', 'User': '00000000', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG1'}]} metto a 1 (chiedi enrico)
# metto mod 5lvl
# metto {'fieldname': 'input_cm_en', 'length': 1, 'registers': [{'REG': '0x17', 'POS': 0, 'RegisterName': 'Input cm settings 1', 'RegisterLength': 8, 'Name': 'input_cm_en', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': 'NNNNNN0N', 'Default': '35', 'User': 'YYYYY0YY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} a 1
#metto {'fieldname': 'cal_mode', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 1, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_mode', 'Mask': '0x2', 'Length': 1, 'FieldMSB': 1, 'FieldLSB': 1, 'Attribute': 'NNNNNNNN', 'Default': '82', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} a zero (con zero e' la modalita ate)
#*********
# {'fieldname': 'cal_offs_steps', 'length': 4, 'registers': [{'REG': '0x76', 'POS': 4, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_steps[3:0]', 'Mask': '0xF0', 'Length': 4, 'FieldMSB': 3, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '82', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} di default fa 8 calibrazioni cercando di convergere a una soglia minina di errore, sono 4 bit, se lo metto a 15 (1111) fa 15 step (consigliato)
# {'fieldname': 'cal_offs_inv_sign', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 3, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_inv_sign', 'Mask': '0x8', 'Length': 1, 'FieldMSB': 3, 'FieldLSB': 3, 'Attribute': 'NNNNNNNN', 'Default': '82', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} e' una mutanda che in caso di errori di cmonunicazione digitali/analogici inverte la polarita della parola di offset (default e' 0 cioe; non inverte. se non funziona la calibrazione la prima cosa da fare e' metterlo a 1) 
# {'fieldname': 'cal_offs_ignore_fault', 'length': 1, 'registers': [{'REG': '0x76', 'POS': 2, 'RegisterName': 'CAL reg 1', 'RegisterLength': 8, 'Name': 'cal_offs_ignore_fault', 'Mask': '0x4', 'Length': 1, 'FieldMSB': 2, 'FieldLSB': 2, 'Attribute': 'NNNNNNNN', 'Default': '82', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} fa in modo di poter scrivere in OTP anche se la procedura fallisce (default 0)
# {'fieldname': 'cal_grp_delay', 'length': 2, 'registers': [{'REG': '0x78', 'POS': 2, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_grp_delay[1:0]', 'Mask': '0xC', 'Length': 2, 'FieldMSB': 1, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} sono 2 bit, serve per aumentare il tempo di attesa tra uno stato e l'altro della macchina a stati, default 500us (01), meglio mettere (10) che e' 1ms
# {'fieldname': 'cal_offs_ext_thr', 'length': 3, 'registers': [{'REG': '0x77', 'POS': 4, 'RegisterName': 'CAL reg 2', 'RegisterLength': 8, 'Name': 'cal_offs_ext_thr[2:0]', 'Mask': '0x70', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '2A', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} (3bit) {'fieldname': 'cal_offs_int_thr', 'length': 3, 'registers': [{'REG': '0x77', 'POS': 0, 'RegisterName': 'CAL reg 2', 'RegisterLength': 8, 'Name': 'cal_offs_int_thr[2:0]', 'Mask': '0x7', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '2A', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]}(3bit) questi sono per la soglia di compensazione (da chiedere ad enrico). il default e' 400uV cioe (010). se voglio scendere guardo la regmap (registro 77 pag0)
# {'fieldname': 'cal_offs_avg', 'length': 3, 'registers': [{'REG': '0x78', 'POS': 4, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_offs_avg[2:0]', 'Mask': '0x70', 'Length': 3, 'FieldMSB': 2, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} (3 bit) decide quanto deve mediare sui campioni se metto (111) sono 128 campioni (consigliato da gianmarco)
# {'fieldname': 'cal_dws_sample_rate', 'length': 2, 'registers': [{'REG': '0x78', 'POS': 0, 'RegisterName': 'CAL reg 3', 'RegisterLength': 8, 'Name': 'cal_dws_sample_rate[1:0]', 'Mask': '0x3', 'Length': 2, 'FieldMSB': 1, 'FieldLSB': 0, 'Attribute': 'NNNNNNNN', 'Default': '57', 'User': 'YYYYYYYY', 'Clocking': 'SMB', 'Reset': 'C', 'PageName': 'PAG0'}]} (2 bit) metto a (11) e' gia default, cambia il sample rate del decimatore del visns (lascia cosi e non toccare)
#**********
# inizio allora la calibrazione con {'fieldname': 'cal_start', 'length': 1, 'registers': [{'REG': '0x79', 'POS': 0, 'RegisterName': 'CAL reg 4', 'RegisterLength': 8, 'Name': 'cal_start', 'Mask': '0x1', 'Length': 1, 'FieldMSB': 0, 'FieldLSB': 0, 'Attribute': '00RR000P', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG0'}]} a 1
#vado in polling sul bit {'fieldname': 'cal_offs_end', 'length': 1, 'registers': [{'REG': '0x79', 'POS': 4, 'RegisterName': 'CAL reg 4', 'RegisterLength': 8, 'Name': 'cal_offs_end', 'Mask': '0x10', 'Length': 1, 'FieldMSB': 4, 'FieldLSB': 4, 'Attribute': '00RR000P', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG0'}]}  e aspetto che diventi 1, che vuoldire che ha finit la calibrazione
#una volta che e' a uno devo andare a vedere {'fieldname': 'cal_offs_result', 'length': 1, 'registers': [{'REG': '0x79', 'POS': 5, 'RegisterName': 'CAL reg 4', 'RegisterLength': 8, 'Name': 'cal_offs_result', 'Mask': '0x20', 'Length': 1, 'FieldMSB': 5, 'FieldLSB': 5, 'Attribute': '00RR000P', 'Default': '00', 'User': 'YYYYYYYY', 'Clocking': 'REF', 'Reset': 'C', 'PageName': 'PAG0'}]}, questo deve essere a 1, se e' a 1 allora la calibrazione ha avuto successo
#il risultato della calibrazione e' salvato in un registro shadow in otp il regitro e' C5 (per external FB, per il per il segno vado in bit 7 di CB) C9 (per internal FB, per il per il segno vado in bit 3 di CB)  
#per sanity check vedo che siano diversi da 0